{{- if not .Values.backend.existingJwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifact-keeper.fullname" . }}-backend
  labels:
    {{- include "artifact-keeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.jwtSecret | quote }}
  MEILISEARCH_API_KEY: {{ include "artifact-keeper.meilisearch.apiKey" . | quote }}
  {{- if .Values.backend.adminPassword }}
  ADMIN_PASSWORD: {{ .Values.backend.adminPassword | quote }}
  {{- end }}
{{- end }}
