-- Migration: index oci_blobs.storage_key for the OCI cleanup sweep's
-- pre-delete liveness re-check (#3085).
--
-- The sweep re-asserts blob liveness immediately before each destructive
-- storage delete. That predicate contains
-- `NOT EXISTS (SELECT 1 FROM oci_blobs b WHERE b.storage_key = k.storage_key)`.
--
-- Before #3085 that subquery ran once per batch, inside the candidate SELECT,
-- so a sequential scan was amortised across the whole batch. The re-check runs
-- it once per candidate, and oci_blobs has no index on storage_key -- migration
-- 118 indexed oci_upload_sessions.storage_temp_key and oci_upload_parts
-- .storage_key, but not this one, because nothing needed it per-row until now.
--
-- Measured on 300k blobs: 87 ms per hold without the index versus 0.19 ms with
-- it; a full 1000-row batch (OCI_UPLOAD_CLEANUP_KEY_SCAN_LIMIT) went from
-- 30.7 s to 0.19 s, ~163x. The cost scales linearly with registry size, so on a
-- large registry a batch would begin to approach the 15 minute claim TTL and
-- leases would lapse mid-sweep.
--
-- CREATE INDEX CONCURRENTLY is intentionally not used here, matching migration
-- 166: sqlx::migrate runs each migration file inside a transaction, and
-- CONCURRENTLY is rejected inside a transaction block. The non-concurrent build
-- takes ACCESS EXCLUSIVE on `oci_blobs` for the duration of the build, so blob
-- uploads block until it finishes. This is a single-column btree on a table that
-- is far smaller than `artifacts` (one row per stored blob, deduplicated by
-- (repository_id, digest)), so the window is short -- but on a large registry,
-- plan the upgrade accordingly.
--
-- Operators who cannot accept the lock window can skip this migration and build
-- the index out of band against a quiescent table:
--
--   CREATE INDEX CONCURRENTLY idx_oci_blobs_storage_key ON oci_blobs (storage_key);
--
-- Correctness does not depend on it: without the index the liveness re-check
-- still returns the right answer, just via a sequential scan. The index is
-- purely a query-plan accelerator.
CREATE INDEX IF NOT EXISTS idx_oci_blobs_storage_key
    ON oci_blobs (storage_key);
